name: flutter_stats
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  collection: ^1.18.0
  community_charts_flutter: ^1.0.4
  csv: ^6.0.0
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.2
  freezed_annotation: ^2.4.1
  intl: any
  json_annotation: ^4.8.1
  provider: ^6.1.1
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
