name: flutter_stats
description: "Calculate your project size in lines of code."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  collection: ^1.18.0
  community_charts_flutter: ^1.0.4
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  distributions: ^0.0.3
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.2
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.3.0
  ml_linalg: ^13.12.6
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.1
  responsive_framework: ^1.4.0
  shared_preferences: ^2.3.2
  universal_html: ^2.2.4
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.8.0
  test: ^1.24.9
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/