name: flutter_stats
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  charts_flutter: ^0.12.0
  collection: ^1.18.0
  csv: ^5.1.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.2
  freezed_annotation: ^2.4.1
  intl: ^0.17.0
  json_annotation: ^4.8.1
  provider: ^6.1.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
